algoritmo "semnome"
// Função :
// Autor :
// Data : 17/09/2020
// Seção de Declarações 
var
   nasc,ano,idade:inteiro
inicio
      escreva("em que ano estamos")
      leia (ano)
      escreva("em que nao voce nasceu")
      leia(nasc)
      idade<-ano-nasc
      escreva("em",ano,"voce tera",idade, "anos.")
      se(IDADE>=18)ENTAO
      ESCREVA ("JA ATINGIO MAIOR DE IDADE")
      SENAO
      ESCREVA("NÃO ANTIGIO E MAIOR DE IDADE")
      FIMSE
fimalgoritmo





